# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: basico-octakit 1.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "basico-octakit"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["rickybell", "renatodex"]
  s.date = "2015-10-13"
  s.description = "A cool Github SDK"
  s.email = "henrique.belloube@gmail.com, renatodex@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "basico-octakit.gemspec",
    "lib/basico-octokit.rb",
    "lib/basico-octokit/config/default.rb",
    "lib/basico-octokit/facade/client.rb",
    "lib/basico-octokit/facade/issues.rb",
    "lib/basico-octokit/helpers/client_helper.rb",
    "lib/basico-octokit/initializers/exceptions.rb",
    "lib/basico-octokit/models/summary.rb",
    "lib/basico-octokit/models/summary_label.rb",
    "lib/basico-octokit/models/summary_user.rb",
    "lib/basico-octokit/models/ticket.rb",
    "lib/basico-octokit/models/ticket_label.rb",
    "lib/basico-octokit/models/ticket_user.rb",
    "lib/basico-octokit/summary_api/issues.rb",
    "lib/basico-octokit/summary_api/summary_collection_array.rb",
    "spec/factories/summary.rb",
    "spec/factories/summary_label.rb",
    "spec/factories/summary_user.rb",
    "spec/factories/ticket.rb",
    "spec/factories/ticket_label.rb",
    "spec/factories/ticket_user.rb",
    "spec/spec_helper.rb",
    "spec/summary_api/issues_spec.rb"
  ]
  s.homepage = "http://github.com/lojabasico/basico-octokit"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Github SDK built on top of Octakit"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<octokit>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<configatron>, [">= 0"])
      s.add_runtime_dependency(%q<colorize>, [">= 0"])
      s.add_runtime_dependency(%q<virtus>, [">= 0"])
      s.add_runtime_dependency(%q<inflecto>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<ffaker>, [">= 0"])
    else
      s.add_dependency(%q<octokit>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<configatron>, [">= 0"])
      s.add_dependency(%q<colorize>, [">= 0"])
      s.add_dependency(%q<virtus>, [">= 0"])
      s.add_dependency(%q<inflecto>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<ffaker>, [">= 0"])
    end
  else
    s.add_dependency(%q<octokit>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<configatron>, [">= 0"])
    s.add_dependency(%q<colorize>, [">= 0"])
    s.add_dependency(%q<virtus>, [">= 0"])
    s.add_dependency(%q<inflecto>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.3.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<ffaker>, [">= 0"])
  end
end

